export { default as OnboardingSlides } from './OnboardingSlides/OnboardingSlides'
export { TOnboardingSlides } from './OnboardingSlides/OnboardingSlides'
export { default as SocialButtonList } from './SocialButtonList/SocialButtonList'
export { TSocialsArray } from './SocialButtonList/SocialButtonList'
export { default as TransactionList } from './TransactionList/TransactionList'
