on: 
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint code
        run: |
          yarn install
          npm run lint
      - name: Test code
        run: |
          yarn install
          npm run test-coverage
